name: Run GitVersion

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup GitVersion
        uses: gittools/actions/gitversion/setup@v4
        with:
          versionSpec: "6.x"

      - name: Execute GitVersion
        uses: gittools/actions/gitversion/execute@v4
        id: gitversion

      - name: Output version
        run: |
          echo "SemVer: ${{ steps.gitversion.outputs.SemVer }}"
          echo "FullSemVer: ${{ steps.gitversion.outputs.FullSemVer }}"
          echo "AssemblySemVer: ${{ steps.gitversion.outputs.AssemblySemVer }}"
          echo "MajorMinorPatch: ${{ steps.gitversion.outputs.MajorMinorPatch }}"

      - name: Create Git tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e

          TAG="v${{ steps.gitversion.outputs.MajorMinorPatch }}"
          echo "Creating tag $TAG"

          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          git tag -a "$TAG" -m "Release ${{ steps.gitversion.outputs.FullSemVer }}"

          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git "$TAG"
