name: CI Pull Request

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  lint-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
          failure-threshold: warning

  scan-docker:
    runs-on: ubuntu-latest
    needs: lint-docker
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -t yandex-terraform:latest .
      - name: Scan with Trivy
        uses: aquasecurity/trivy-action@0.33.1
        with:
          scan-type: image
          image-ref: yandex-terraform:latest
          severity: CRITICAL,HIGH,MEDIUM
          ignore-unfixed: false
