name: Publish Docker Image

on:
  push:
    branches:
      - main
    tags:
      - "v*"

permissions:
  contents: read

jobs:
  publish-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Latest Tag
        id: get_tag
        run: |
          LATEST_TAG=$(git describe --tags --abbrev=0)
          echo "tag=$LATEST_TAG" >> $GITHUB_OUTPUT

      - name: Print Tag to Console
        run: |
          echo "Latest tag: ${{ steps.get_tag.outputs.tag }}"

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            stupean/yandex-terraform:latest
            stupean/yandex-terraform:${{ steps.get_tag.outputs.tag }}
